### ISSUE TITLE
If you fall behind, you will be beaten

### ISSUE THREAD

**Issue by Dream-Ling** [1995parham/github-do-not-ban-us#1479]
There is no absolute equality in this world. When you lose your equality,All complaints were of no use.

**Comment by scvoet** [comment]
Without absolute equality, it is up to us to create relative equality. You can see that many people are proposing to build a new platform, and you can also see the changes that GitHub has made because of this project. I hope that you can understand that this is the reason for man-made.
---------------
没有绝对的平等，那就由我们来创造相对的平等。您可以看见有很多人在提议建立一个新的平台，您也可以看见GitHub因为这个项目而发生的改变。我希望您能够明白事在人为这个道理。

**Comment by Dream-Ling** [comment]
What us create, we see as equal, may not be.

**Comment by ovflowd** [comment]
@1995parham could you close this Issue? It looks like an offense 😅
