### ISSUE TITLE
First they came...

### ISSUE THREAD

**Issue by arthurkiller** [1995parham/github-do-not-ban-us#1507]
They first came for the Communists,
and I didn't speak up
because I wasn't a Communist.
Then they came for the Jews,
and I didn't speak up
because I wasn't a Jew.
Then they came for the trade unionists,
and I didn't speak up
because I wasn't a trade unionist.
Then they came for the Catholics,
and I didn't speak up
because I was a Protestant.
Then they came for me,
but by that time,
there was no one left to speak up.

__support from Chinese developer__

**Comment by scvoet** [comment]
You are silent now, because you have not persecuted you yet. When they persecute you, you blame no one in this society to help you. We all know who is coming to sin first. Silence is also a sin.We are now speaking to the restricted users, and some people will speak for us in the future.
----------
你现在沉默，因为还没有迫害到你。当他们迫害你时，你却又责怪这个社会没有人帮助你。我们都清楚罪恶先降临在谁的身上。沉默也是一种罪恶。我们现在为被限制的用户发声，以后也会有人为我们发声。

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
