### ISSUE TITLE
Are we getting censored by Github?

### ISSUE THREAD

**Issue by mmahmoudian** [1995parham/github-do-not-ban-us#1588]
Out of curiosity I went to check where this repo is in the [trending repos in Github](https://github.com/trending). 

First, few facts:
1. This repo started around 2019.07.20 (based on the [code frequency](https://github.com/1995parham/github-do-not-ban-us/graphs/code-frequency)) -> [Figure01](#figure01) 
2. This repo has, at the time of writing this, 10,979 stars -> [Figure01](#figure01) 

i then went to Trends page and sorted it by [This week](https://github.com/trending?since=weekly) and [This month](https://github.com/trending?since=monthly), hoping to see this repo at top of the list, but I could not find it in the lists -> [Figure02](#figure02)  and [Figure03](#figure03) 

This begs the question: Are we getting censored by Github?

I also archived these pages in archive.org for the record:
- https://web.archive.org/web/20190801114300/https://github.com/trending?since=monthly
- https://web.archive.org/web/20190801115104/https://github.com/trending?since=weekly

## Figure01
![image](https://user-images.githubusercontent.com/390889/62289756-3036b180-b468-11e9-9901-257a108f8bd3.png)

## Figure02
![image](https://user-images.githubusercontent.com/390889/62290054-08941900-b469-11e9-8449-d0253a4fd512.png)

## Figure03
![image](https://user-images.githubusercontent.com/390889/62290037-fc0fc080-b468-11e9-9e47-0bb9d5326665.png)

**Comment by 1995parham** [comment]
We are at the trending list only for two days and they remove us today again.

**Comment by demuh** [comment]
Such a shameful act if it's true.

**Comment by Alir3z4** [comment]
Oh yes, it's obvious they would do it.

Although they will not confirm it since it's their algo that does something and we're obviously too dumb to understand.

In any case, I don't think this repo will gain much.
Yes, it had took some attention, some reddit high votes, some news outlets, something here and something there.

At the end, we're talking about "3rd world countries", where "human rights" doesn't mean anything and in most cases population from such places are considered sub-humans, you may don't like it but that's a reality.

I'm sure you remember terrorist attack  happening in Iran Majlis and suicide bomb that happened in Imam Khomeini Shrine. It only took some tiny comments on reddit and news outlets barely reporting it, but when it's from a white/west country, it will explode the news and everyone will cry and change their pictures for the victim.

I can't blame the people, It's just how media has portrayed us and as individual and even groups or organizations or even states we don't have a chance with their most powerful weapon (_da media!!!_). 

Why I'm saying this, is that, don't hold much hope for such awareness and don't even hope that exposing censorship of such platforms will get anywhere. They have gotten away with such horrific acts and mass murdering and lying that is even beyond imagination and those who you may think them as protractor of freedom, human rights (خوانده شود: حقوق حشر) civilization etc are simply the ones pushing the agenda.

Limiting Github access is nothing, absolutely nothing in compared other things they're doing.

Dude, they're killing people by sanctioning medicine and inflation and no ones gives a damn, do you think a website that most of the population outside of development and tech that don't know nothing about would care ? I know IT people that have no idea what Github is.

Me, you and many more like me and you, are simply portrayed as dangerous, savages and blood thirsty and no-worthy. Don't be fooled with some video clips on youtube and some articles saying nice things about us, the default factory setting is, we're the bad wolf and a danger to the freedom and democracy of the west.

This is all political with tons of spices of personal.

**Comment by FIREFOXCYBER** [comment]
Well it's still there: https://trends.now.sh

**Comment by ovflowd** [comment]
Well, If I was GitHub I would also block this repository from the trending list, and the reason is simple:

This repository isn't about code, bout about politics, and If GitHub by any means show this in trending, the US government could blame GitHub for giving the banned countries a political voice.

But as a human, I personally don't agree with GitHub removing this repository from the Trending list (Actually it may be part of the Algorithm, we really don't know).

Anyways, probably they had to do that (blocking) for the reasons that I stated.

**Comment by 1995parham** [comment]
@ovflowd Thanks for supporting us in this movement and trying to describe some of our circumstances in the vision of GitHub. I think you are right about GitHub conditions and as always we want to do respect to us as their users and try to understand us. I do my best to keep this movement away from politics and I just want to inform users about our restrictions and make GitHub respect us and I think we have some of our objectives.
