### ISSUE TITLE
Microsoft, Sorry for the Decision!

### ISSUE THREAD

**Issue by MAChitgarha** [1995parham/github-do-not-ban-us#295]
First of all, thank you everyone who joined here and support this!

And a special sorry-ness to Microsoft, because of its bad decisions. Why you would restrict private repositories of Iranian users, without any alerts (AFAIK)? Oh, I forgot, just like Windows Updates. You don't inform changes in your services, sometimes. [See here](https://github.com/1995parham/github-do-not-ban-us/blob/master/together/MAChitgarha/github-is-for-everyone.php)!

**Comment by jhpratt** [comment]
Microsoft determined that they had to block users due to sanctions. Any delay in doing so would be willful violation of those sanctions, and therefore illegal.

**Comment by MAChitgarha** [comment]
@jhpratt How about not blocking by IP, and blocking the accounts?

**Comment by jhpratt** [comment]
Then it would be trivial to bypass with a VPN — Microsoft isn't stupid, they're enforcing the law and limiting the simple "loopholes".

**Comment by ovflowd** [comment]
Again, Microsoft has 0 power for interfering; This is not related at al to Microsoft.

**Comment by ovflowd** [comment]
https://github.com/1995parham/github-do-not-ban-us/blob/master/together/MAChitgarha/github-is-for-everyone.php and this file is a really big offense, both for open source and developers. You contradict yourself when you say "let develop cool things" and in the next paragraph you literally use a combination of bad words. Blaming a company that actually is the today's biggest supporter for open source and community for something that isn't even their fault, is like being blind.

Microsoft is supporting really hard diversity, inclusion and open source; Also they really have a big effort in hearing the users and doing what they want. Microsoft from today isn't the same from 10 years ago.

**Comment by MAChitgarha** [comment]
@ovflowd I told my idea, because of some Microsoft decisions. I didn't want to say that the whole Microsoft is bad (but it seems I said). I'm using Visual Studio Code and like it, and also Outlook email.

However, I still mind that Microsoft is far from a good company. Microsoft sometimes do things so bad. Apologizing from this decision? No. Any alerts? No. Blocking by IP, to allow us use a VPN? No. These 'No's makes sense.

**Comment by MAChitgarha** [comment]
@ovflowd But yes, it was a bit bad. #891

**Comment by ovflowd** [comment]
@MAChitgarha at least give a look to Nat Friedman (GitHub CEO) tweets. He totally support Iran. You can't just guess that Microsoft or/and GitHub didn't **wanted** to give notices or alerts. They just can't.

Also again, Microsoft can't interfere with GitHub and they don't "command" GitHub. GitHub is 100% independent from Microsoft.

Actually using a VPN to "bypass" would be illegal, so...

I can understand the feeling, but complaining about something that it's just not true, it's pointless and offensive.

PS: today's Microsoft isn't a bad company. They really are WORKING super hard to help people, communities, students, refugees, poor people, and to empower minorities and etc. They are doing an amazing work, if you're not aware of that, it's just your fault for not looking the news, but I'm not blaming you. Everyone has the "freedom" to believe in whatever they want :)

I can relate that in the moment you were mad and you don't really have bad intentions on that. But just remember, this is a public repo, were many people are seeing. And if you WANT the support from people, being polite is important, if you don't want to people to get you wrong.

I'm just trying to give some advise ;)

**Comment by MAChitgarha** [comment]
@ovflowd 

> At least give a look to Nat Friedman (GitHub CEO) tweets. He totally support Iran. You can't just guess that Microsoft or/and GitHub didn't wanted to give notices or alerts. They just can't.
I don't totally agree with you. I've read his tweets. They can. Many people have paid for their accounts. What about user privacy? How about [this](https://slackhq.com/an-apology-and-an-update)?

> I can relate that in the moment you were mad and you don't really have bad intentions on that.
Maybe. And maybe because I'm a Linux fan! :)

> I'm just trying to give some advise ;)
Thank you. But the words were not as offensive as you say.

**Comment by ovflowd** [comment]
You're always assuming they can, what proofs you have they can? C'mon you just want to believe on that because it looks better for your cause. 

Reality is different.

I'm a Linux user, and I'm a long term open source contributor. Liking Linux doesn't mean that you need to hate Microsoft. A lot of Microsoft employees uses Linux, and what?

You're just giving lame excuses to your actions. Your excuse it totally doesn't make sense at all.

**Comment by MAChitgarha** [comment]
@ovflowd 
> I'm a Linux user, and I'm a long term open source contributor. Liking Linux doesn't mean that you need to hate Microsoft. A lot of Microsoft employees uses Linux, and what?
Actually. It was just a joke. Don't mention it!

> You're just giving lame excuses to your actions. Your excuse it totally doesn't make sense at all.
We are all humans. We make mistakes. Actually, I made a mistake for bad words. I'm trying to say the mistake wasn't just that big.

> You're always assuming they can, what proofs you have they can? C'mon you just want to believe on that because it looks better for your cause.
Proofs? Not respecting users is a mistake from a big company, whether it's Google or Microsoft. It doesn't matter. Their action could be really friendlier.

**Comment by ovflowd** [comment]
Well @MahdiGhiasi If you were doing a joke, I'm no one to blame you :)

I know we're all humans, we do mistakes, but still, here's an open public repository with 5 thousand stars and where a lot of attention is going on right now... Joking with this isn't cool.... :/

@MAChitgarha I can assure you that GitHub always (or almost) people, and that they work after it. I contributed to their Education team, and being honest I never get to know a Company that is **MORE** dedicated to help the community, users and people rather than GitHub. Just look the news, what GitHub is trying to do in India, in Sri Laika. That's why I'm pissed. Because something unfair happened with you and the Iranians, and I **totally support** but the first thing you do, is blaming Microsoft (that has nothing to do with this) and GitHub that **IS ACTUALLY** in this exactly moment, trying to create a solution to this whole big mess.

The reason why they didn't published any official statement? Because they can't yet, because right now they're working in something to help y'all. And that's how you treat the very own company...

I know you don't have bad intentions, but dude, think before you assume something like that; Because it break hearts. Check some other issues from this repository, it's heartbreaking.

If you want to know more about what GitHub does for their community, give a look in the GitHub Satellite Keynote for example; GitHub is one of the few companies that is always, ALWAYS, working after their users, developers and communities.

I'm sorry if you're just angry and pissed, I would also be pissed if this happens to me, but GitHub is not the organisation you should blame, but YES the US government.

Thank you.

**Comment by MAChitgarha** [comment]
@ovflowd

Really thanks for your attention and answers. I never wanted to say GitHub developers, maintainer and supporters are bad. And yes, I should not break hearts.

You're right. I'm going to close this issue at the right moment. Thanks for all your advices, that looks really helpful to change my mind. ;)

And would you recommend deleting it?

**Comment by ovflowd** [comment]
I don't want to be right, just want to show that the story could be a little different from what you think it is. But still, I may be totally wrong after all.

You don't need to apologise dude. You just defended your thoughts, and that's what make us humans after all.

I don't think you need delete it, it could be a good source for people that also may think similar.

And, I don't think you breaked any hearts 😉

I wish US unban your country and all others ASAP, you and all Iranians deserve better
.

**Comment by gusbemacbe** [comment]
I have a question. Can US sanctions against certain countries affect FOSS products, @ovflowd ?

**Comment by ovflowd** [comment]
Hey, I'm not sure, it may depend on the LICENSE. But I hope we don't get in the day where FOSS may be restricted in that way, it would be really sad 😨

**Comment by gusbemacbe** [comment]
I hope not. If all the FOSS projects, and also Linux, independently of the place are forced to comply with the US trade law, it can impact the diplomatic relations between every country and the US.
