### ISSUE TITLE
The real reason this is happening

### ISSUE THREAD

**Issue by ShayBox** [1995parham/github-do-not-ban-us#505]
The reason this is happening has nothing to do with Microsoft or GitHub, so how about we stop shitting on Microsoft and GitHub like they randomly chose to do this, point your guns at the government, GitHub cant do anything about it, they're a US based company and would have had to do this even if Microsoft didn't own it, other websites are having to do similar things.

So how about we stop closing the issues & prs talking about the real problem, stop pushing your agenda, it's not making you look good.

**Comment by xlxs4** [comment]
GitHub could notify its users before restricting their access, as well as it could just restrict Iranian IPs, instead of Iranians

**Comment by joshudson** [comment]
Full disclosure: I am no part of GitHub, not even a single share of stock in github's owner (Microsoft) I am a citizen of USA by birth.

By law, GitHub is not allowed to take Iranians money. I suppose they could offer all the free-to-use features, but there is no chance the pay-to-use features are coming back. GitHub would not get away with giving away the pay-to-use features assuming they wanted to, so there's no point asking.

I still think they should have just flipped all the repositories to read-only.

**Comment by BelegCuthalion** [comment]
@ShayBox There is no single reason. But I agree, the situation here is caused by the US law, which in turn is caused by US violation of an multilateral agreement, which in turn is caused by historic tension between Iran and US, which in turn is caused by historical and geopolitical causes... The list keeps going on, you may expand it further, and many of its items, IMO, deserve to be protested against, what I personally do. But it is also in accord with what we are doing here. Either if it is putting pressure on someone who can affect US policies against us, or bringing hypocritical appeal of US government/companies to the public, or just informing people so at least they have a more accurate notion of what they really mean by liberty and diversity, and all other social trends and buzz words they take advantage of daily.

**Comment by joshudson** [comment]
Or you can put pressure on the Iranian people to overthrow their government. Shrug.

**Comment by BelegCuthalion** [comment]
@joshudson Well, basically, I see a little change in US aggressive behavior more reasonable, but for the matter at hand, what [this repo is actually trying to achieve](README.md) is very simple clear.

> Or you can put pressure on the Iranian people to overthrow their government.

That's good idea, but it's not for this repo. I suggest starting an "Iranian-people-overthrow-your-government" campaign and continue this conversation there. I'm sure you'll gain much support from DC—probably in cash.

Ps. Or wait... Isn't that basically what US government has been doing? Sorry mate, I'm afraid your a few 60 years late with the idea.

**Comment by labadore** [comment]
What really disgusts me is the focus on nationality. There are so many problems with this approach I don't even know where to begin; this is straight up profiling users. I can understand the need to comply with aggressive US law, but this is far more aggressive than the minimum compliance necessary.

This kind of thing doesn't belong here, _period_. It's nothing short of politicization. There are many talented developers all over the world that are affected by this that we all lose out on.

**Comment by jgierer12** [comment]
> Or you can put pressure on the Iranian people to overthrow their government. Shrug.

What a nice euphenism for "Or you can force the Iranian people to risk their lives if they want to keep their job. Shrug."

**Comment by runvnc** [comment]
I think people are not realizing the actual context and scope of this conflict.  It goes back hundreds of years.  https://en.m.wikipedia.org/wiki/Roman%E2%80%93Persian_Wars   http://www.iranicaonline.org/articles/crusades-in-relation-to-persia https://en.m.wikipedia.org/wiki/Anglo-Persian_War and https://en.m.wikipedia.org/wiki/The_Great_Game as well as https://en.m.wikipedia.org/wiki/Iran%E2%80%93United_States_relations

**Comment by ShayBox** [comment]
The entire point of the change is to block people, providing an easy way to work around it would be stupid, and if you're advocating for them to have had done it differently to allow people to work around it, you clearly don't see the point, you're not supposed to be able to use github, this isnt some stupid backhand thing where you ask your mom for something, she says no then your dad secretly gives it to you, you're actually not allowed to use the service, and wanting a way around it is just breaking the law.

**Comment by labadore** [comment]
It's almost as if the law is wrong or something

**Comment by BelegCuthalion** [comment]
@ShayBox There are many things you keep missing here. If your explanation has also addressed these issues, please help me find them, cause I can't.
  - You can't say when a service is subject to sanctions. There are many services based in US that are not restricted (yet), and there are ones (including free ones) that are, which seem to result from apologetic and arbitrary interpretation of the sanctions. There are even services, like GitLab, which does not enforce any restrictions, but are eventually restricted by their infrastructure. So I'm still not sure it is a matter of *being subject to sanctions* or *compliance with US policies*, specially when US gov's public gesture is *"sanctions are not meant to target civilians"* and *"we don't restrict information technology and free flow of communication"*.
  - AFAIK, with exception of paid services, all other companies that have imposed any kind of restrictions on their Iranian users, implemented them by means that could easily be bypassed, more specifically, they use IP range. Don't they know this? Of course they do. And this seems like a simple and effective way to both submit to the US government and also keep their users. Why US gov have done nothing about it? Personally I believe that's because the point is not really to block people—you don't really think this will make you safer, do you? Nor the US government thinks so, I guess. It is probably considered sufficient compliance, as long as the sanctions play their psycho-warfare role. I don't know if there was a special government agent for GitHub that told them to implement it exactly as they tell them to, but other than this, they could also behave like other US companies.
  - Even if—for any reason—they also felt responsible for possible bypass of the sanctions by their users, there are still things they could consider. Like warning users and giving them choice to leave GitHub before taking their data hostage. Or publicly announcing the extent and methods of enforcing their policy. That's not considered a workaround, right?
  - We are not demanding them to risk their interests in favor of free software by resisting US government; it is trivially too much to ask. Also this repo is not about convicting someone as the *only cause* of the situation and pardoning anyone else. Every party to this situation, including US gov., Iran gov., developers, UN, ... has responsibilities that can be called into question. This repo is about GitHub's part of the bargain. Others are just questioned, proportional to their responsibilities, *separately*.
  - GitHub's responsibilities are not summarized in giving people access to their data. They are not even obligated to provide any service to a certain group of people at all, let's assume. The point is that GitHub is also responsible for the gesture it poses to the public about certain *values* that they respect, which clearly contradicts what they are doing now. Your granny can adore them as good people with attitude, but their gain from this posture absolutely does not stop here. So they must pay a price, actually more than what they pay to the designers, for what they're taking advantage of, as many others do. Or stop fooling people and announce publicly "We support values foo and bar, only up to this point, we can't bear more expenses." That simple.

**Comment by BelegCuthalion** [comment]
@ShayBox So they probably either gonna face punishments, or they could do this #666 from the very first.

**Comment by dgorodnichy** [comment]
Github could do as Slack. A lot of usa companies working with Iran or Cuba users. But github ban users by their nationality. It's github decision, not us government. Github and Microsoft are evil, and it's reason of bans.
