### ISSUE TITLE
Categorize Countries

### ISSUE THREAD

**Issue by MAChitgarha** [1995parham/github-do-not-ban-us#575]
One idea can be categorizing countries in the Supporters section. This can look really better. The flag can also be put on each country sub-section, next to the country name. However, there are some things to be noted:

1. People with two countries mentioned; about five or six people we have I think. The first country they mentioned will be considered as their main one.

2. People without any countries; around ten to fifteen people. They might be grouped as 'Not Mentioned' (a no-flag emoji should be put).

3. Order in the countries. Not an exactly idea about this. My suggestion is to order them by the users count, but keep it unchanged for future pull requests.

Would you accept this?

**Comment by MAChitgarha** [comment]
@pesehr Any ideas?

**Comment by MAChitgarha** [comment]
@pesehr Should I do that, and make a pull request?

**Comment by MAChitgarha** [comment]
@1995parham @pesehr Here is the pull request: #754

**Comment by pi0** [comment]
We are all the same! Categorizing is not a good idea imo.

**Comment by MAChitgarha** [comment]
@pi0 Please continue the discussion [here](754).

**Comment by 1995parham** [comment]
@MAChitgarha We have many pull request and we cannot merge your pull request because it causes many conflicts and that cannot resolve easily. Now we have time for doing that. As @pi0 said we think sorting supporters is good but distribute them by countries may not be so good. If you want we have an issue for providing a sort script that can be run on ci. #389 
In the end, we are so grateful for all of your support and contribution to this movement.

**Comment by MAChitgarha** [comment]
@1995parham Thanks for your response. Well, ordering alphabetically is a good idea too.
