### ISSUE TITLE
#ScrewGitHub

### ISSUE THREAD

**Issue by abdolrezat** [1995parham/github-do-not-ban-us#707]
It's a shame they want us out, as an alternative consider using GitLab

**Comment by fakefred** [comment]
@abdolrezat Back in July 2018, GitLab annonced migration from Azure to Google Cloud Platform.

> NOTE to users in Crimea, Cuba, Iran, North Korea, Sudan, and Syria: GitLab.com may not be accessible after the migration to Google. Google has informed us that there are legal restrictions that are imposed for those countries. See this U.S. Department of the Treasury link for more details. At this time, we can only recommend that you download your code or export relevant projects as a backup. See this issue for more discussion.

[Update on our planned move from Azure to Google Cloud Platform | GitLab](https://about.gitlab.com/2018/07/19/gcp-move-update/)

Screwing is not enough. It's like moving from New York to Hawaii. See [my issue](https://github.com/1995parham/github-do-not-ban-us/issues/629) that proposes a federated git hosting network. Spread the idea of #FederatedGit. Instead of screwing, we crack down this problematic system that lies in our way to complete software freedom.

**Comment by ovflowd** [comment]
GitLab also has the same trading bans, just for saying.

And it's not GitHub that wants you OUT. Is the US government.

**Comment by ovflowd** [comment]
![image](https://user-images.githubusercontent.com/12037269/62010027-c5366380-b165-11e9-8cda-167bc875e573.png)

Pretty much this image explains it. And I need to say, If GitHub was able to do something, they would.

**Comment by gnFur** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/12037269/62010027-c5366380-b165-11e9-8cda-167bc875e573.png)
> 
> Pretty much this image explains it. And I need to say, If GitHub was able to do something, they would.

Smells like a load of bullshit. They knew in advance this will be happening, it's not illegal to inform users about this. They didn't even bothered to make an official statement until shit hit the fan.

**Comment by ovflowd** [comment]
Smells like a load of b? Man, look your tongue.

How can you be sure that is a load of b? Do you even know Nat? I don't think so. Because if you would, you weren't saying this.

Feel free to complain what you want, being honest, if you want to believe on that, feel free, you're free to complain.

**Comment by gnFur** [comment]
> 
> 
> Smells like a load of b? Man, look your tongue.
> 
> How can you be sure that is a load of b? Do you even know Nat? I don't think so. Because if you would, you weren't saying this.
> 
> Feel free to complain what you want, being honest, if you want to believe on that, feel free, you're free to complain.

I don't need to know him to see that this is just damage control. Why didn't he or Github itself made a statement before? Why didn't he made sure people are notified? Why does he lie in his tweet that it's somehow illegal to warn those who are affected? This was handled in the worst way possible, I see no reason to look my tongue.

**Comment by ovflowd** [comment]
You're not happy? Move to GitLab. But stop saying stuff that you don't know for sure, I mean you're free to believe and say whatever you want. It's just sad how much hate you have on you heart, dude.

**Comment by gnFur** [comment]
> You're not happy? Move to GitLab
This is exactly what I'm gonna do. Bitbucket, here I go. =]

He may be the nicest lad in the world in person, but I don't care as long as his actions show otherwise.

**Comment by ovflowd** [comment]
Dude, you don't even know what's happening understood...

And yeah, which actions are you referring? Because you're assuming that he made an executive order or something like "just block all the people from the US trade section right now"? Of course not. Who takes these actions are the Legal Personnel inside GitHub.

I should stop.commenting here, I see that I probably will not change your mind 😕

**Comment by ovflowd** [comment]
Another thing, i suppose you know how companies work, because be rested that it wasn't a decision made by Nat at all. Also, be advised that in this exactly moment GitHub is working on everything that is possible to get the situation better. The reason why there's no public announce yet, is because they can't, because they're doing the stuff right now. And they already shipped a feature to at least make the blocked repositories visible again.

And also, I'm being honest when I say, that when the UD government emitted the action, they literally had to follow the action ASAP. Without period for notice.

**Comment by 1995parham** [comment]
Thanks for your support
We are really glad that you support us from your country.
Please support us by sharing this repository and #githubforeveryone.
